[package]
name = "ckb-rpc-gen"
version = "0.114.0-pre"
edition = "2021"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
description = "CKB RPC documentation generator"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-rpc ={ path = "../../../rpc", version = "= 0.114.0-pre" }
schemars = { version = "0.8.16", package = "ckb_schemars" }
serde_json = "~1.0"
tera = "1"
