[package]
name = "ckb-indexer"
version = "0.114.0-rc3"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "The ckb indexer"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
rocksdb = { package = "ckb-rocksdb", version ="=0.21.1", features = ["snappy"], default-features = false }
ckb-db-schema = { path = "../../db-schema", version = "= 0.114.0-rc3" }
ckb-types = { path = "../types", version = "= 0.114.0-rc3" }
ckb-jsonrpc-types = { path = "../jsonrpc-types", version = "= 0.114.0-rc3" }
ckb-logger = { path = "../logger", version = "= 0.114.0-rc3" }
ckb-app-config = { path = "../app-config", version = "= 0.114.0-rc3" }
ckb-notify = { path = "../../notify", version = "= 0.114.0-rc3" }
ckb-store = { path = "../../store", version = "= 0.114.0-rc3" }
ckb-stop-handler = { path = "../stop-handler", version = "= 0.114.0-rc3" }
ckb-async-runtime = { path = "../runtime", version = "= 0.114.0-rc3" }
rhai = { version = "1.10.0", features = ["no_function", "no_float", "no_module", "sync"]}
serde_json = "1.0"
numext-fixed-uint = "0.1"
memchr = "2.7"

[dev-dependencies]
tempfile.workspace = true
rand = "0.8"
faster-hex = "0.6"
